#ifndef COMMANDS_HPP
#define COMMANDS_HPP

#include "Commands/conclusionaddcommand.hpp"
#include "Commands/conclusionchangecommand.hpp"
#include "Commands/conclusiondeletecommand.hpp"
#include "Commands/conclusionmovecommand.hpp"
#include "Commands/domainaddcommand.hpp"
#include "Commands/domaindeletecommand.hpp"
#include "Commands/domainmovecommand.hpp"
#include "Commands/domainrenamecommand.hpp"
#include "Commands/premiseaddcommand.hpp"
#include "Commands/premisechangecommand.hpp"
#include "Commands/premisedeletecommand.hpp"
#include "Commands/premisemovecommand.hpp"
#include "Commands/reasoningchangecommand.hpp"
#include "Commands/ruleaddcommand.hpp"
#include "Commands/ruledeletecommand.hpp"
#include "Commands/rulemovecommand.hpp"
#include "Commands/rulerenamecommand.hpp"
#include "Commands/valueaddcommand.hpp"
#include "Commands/valuedeletecommand.hpp"
#include "Commands/valuemovecommand.hpp"
#include "Commands/valuerenamecommand.hpp"
#include "Commands/variableaddcommand.hpp"
#include "Commands/variablechangecommand.hpp"
#include "Commands/variabledeletecommand.hpp"
#include "Commands/variablemovecommand.hpp"
#include "Commands/variablerenamecommand.hpp"

#endif // COMMANDS_HPP
