#############################################################################
# Makefile for building: yax
# Generated by qmake (2.01a) (Qt 4.7.4) on: Mon Nov 28 16:57:25 2011
# Project:  yax.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile yax.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		domainsdockwidget.cpp \
		YAXCore/yaxmodels.cpp \
		variablesdockwidget.cpp \
		rulesdockwidget.cpp \
		YAXCore/yaxvariablesmodel.cpp \
		YAXCore/yaxvaluesmodel.cpp \
		YAXCore/yaxdomainsmodel.cpp \
		YAXCore/yaxrulesmodel.cpp \
		YAXCore/rulestreeitem.cpp \
		YAXCore/rulesdelegate.cpp moc_mainwindow.cpp \
		moc_domainsdockwidget.cpp \
		moc_yaxmodels.cpp \
		moc_variablesdockwidget.cpp \
		moc_rulesdockwidget.cpp \
		moc_yaxvariablesmodel.cpp \
		moc_yaxvaluesmodel.cpp \
		moc_yaxdomainsmodel.cpp \
		moc_yaxrulesmodel.cpp \
		moc_rulesdelegate.cpp
OBJECTS       = main.o \
		mainwindow.o \
		domainsdockwidget.o \
		yaxmodels.o \
		variablesdockwidget.o \
		rulesdockwidget.o \
		yaxvariablesmodel.o \
		yaxvaluesmodel.o \
		yaxdomainsmodel.o \
		yaxrulesmodel.o \
		rulestreeitem.o \
		rulesdelegate.o \
		moc_mainwindow.o \
		moc_domainsdockwidget.o \
		moc_yaxmodels.o \
		moc_variablesdockwidget.o \
		moc_rulesdockwidget.o \
		moc_yaxvariablesmodel.o \
		moc_yaxvaluesmodel.o \
		moc_yaxdomainsmodel.o \
		moc_yaxrulesmodel.o \
		moc_rulesdelegate.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		yax.pro
QMAKE_TARGET  = yax
DESTDIR       = 
TARGET        = yax

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: yax.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile yax.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile yax.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/yax1.0.0 || $(MKDIR) .tmp/yax1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/yax1.0.0/ && $(COPY_FILE) --parents mainwindow.hpp domainsdockwidget.hpp YAXCore/yaxmodels.hpp variablesdockwidget.hpp rulesdockwidget.hpp YAXCore/yaxkb.hpp YAXCore/yaxvariablesmodel.hpp YAXCore/yaxvaluesmodel.hpp YAXCore/yaxdomainsmodel.hpp YAXCore/yaxrulesmodel.hpp YAXCore/rulestreeitem.hpp YAXCore/rulesdelegate.hpp .tmp/yax1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp domainsdockwidget.cpp YAXCore/yaxmodels.cpp variablesdockwidget.cpp rulesdockwidget.cpp YAXCore/yaxvariablesmodel.cpp YAXCore/yaxvaluesmodel.cpp YAXCore/yaxdomainsmodel.cpp YAXCore/yaxrulesmodel.cpp YAXCore/rulestreeitem.cpp YAXCore/rulesdelegate.cpp .tmp/yax1.0.0/ && (cd `dirname .tmp/yax1.0.0` && $(TAR) yax1.0.0.tar yax1.0.0 && $(COMPRESS) yax1.0.0.tar) && $(MOVE) `dirname .tmp/yax1.0.0`/yax1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/yax1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_domainsdockwidget.cpp moc_yaxmodels.cpp moc_variablesdockwidget.cpp moc_rulesdockwidget.cpp moc_yaxvariablesmodel.cpp moc_yaxvaluesmodel.cpp moc_yaxdomainsmodel.cpp moc_yaxrulesmodel.cpp moc_rulesdelegate.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_domainsdockwidget.cpp moc_yaxmodels.cpp moc_variablesdockwidget.cpp moc_rulesdockwidget.cpp moc_yaxvariablesmodel.cpp moc_yaxvaluesmodel.cpp moc_yaxdomainsmodel.cpp moc_yaxrulesmodel.cpp moc_rulesdelegate.cpp
moc_mainwindow.cpp: domainsdockwidget.hpp \
		YAXCore/yaxmodels.hpp \
		YAXCore/yaxkb.hpp \
		YAXCore/yaxdomainsmodel.hpp \
		YAXCore/yaxvaluesmodel.hpp \
		YAXCore/yaxvariablesmodel.hpp \
		YAXCore/yaxrulesmodel.hpp \
		YAXCore/rulestreeitem.hpp \
		variablesdockwidget.hpp \
		rulesdockwidget.hpp \
		YAXCore/rulesdelegate.hpp \
		mainwindow.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.hpp -o moc_mainwindow.cpp

moc_domainsdockwidget.cpp: YAXCore/yaxmodels.hpp \
		YAXCore/yaxkb.hpp \
		YAXCore/yaxdomainsmodel.hpp \
		YAXCore/yaxvaluesmodel.hpp \
		YAXCore/yaxvariablesmodel.hpp \
		YAXCore/yaxrulesmodel.hpp \
		YAXCore/rulestreeitem.hpp \
		domainsdockwidget.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) domainsdockwidget.hpp -o moc_domainsdockwidget.cpp

moc_yaxmodels.cpp: YAXCore/yaxkb.hpp \
		YAXCore/yaxdomainsmodel.hpp \
		YAXCore/yaxvaluesmodel.hpp \
		YAXCore/yaxvariablesmodel.hpp \
		YAXCore/yaxrulesmodel.hpp \
		YAXCore/rulestreeitem.hpp \
		YAXCore/yaxmodels.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) YAXCore/yaxmodels.hpp -o moc_yaxmodels.cpp

moc_variablesdockwidget.cpp: YAXCore/yaxmodels.hpp \
		YAXCore/yaxkb.hpp \
		YAXCore/yaxdomainsmodel.hpp \
		YAXCore/yaxvaluesmodel.hpp \
		YAXCore/yaxvariablesmodel.hpp \
		YAXCore/yaxrulesmodel.hpp \
		YAXCore/rulestreeitem.hpp \
		variablesdockwidget.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) variablesdockwidget.hpp -o moc_variablesdockwidget.cpp

moc_rulesdockwidget.cpp: YAXCore/yaxmodels.hpp \
		YAXCore/yaxkb.hpp \
		YAXCore/yaxdomainsmodel.hpp \
		YAXCore/yaxvaluesmodel.hpp \
		YAXCore/yaxvariablesmodel.hpp \
		YAXCore/yaxrulesmodel.hpp \
		YAXCore/rulestreeitem.hpp \
		YAXCore/rulesdelegate.hpp \
		rulesdockwidget.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) rulesdockwidget.hpp -o moc_rulesdockwidget.cpp

moc_yaxvariablesmodel.cpp: YAXCore/yaxkb.hpp \
		YAXCore/yaxvariablesmodel.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) YAXCore/yaxvariablesmodel.hpp -o moc_yaxvariablesmodel.cpp

moc_yaxvaluesmodel.cpp: YAXCore/yaxkb.hpp \
		YAXCore/yaxvaluesmodel.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) YAXCore/yaxvaluesmodel.hpp -o moc_yaxvaluesmodel.cpp

moc_yaxdomainsmodel.cpp: YAXCore/yaxkb.hpp \
		YAXCore/yaxdomainsmodel.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) YAXCore/yaxdomainsmodel.hpp -o moc_yaxdomainsmodel.cpp

moc_yaxrulesmodel.cpp: YAXCore/rulestreeitem.hpp \
		YAXCore/yaxkb.hpp \
		YAXCore/yaxrulesmodel.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) YAXCore/yaxrulesmodel.hpp -o moc_yaxrulesmodel.cpp

moc_rulesdelegate.cpp: YAXCore/rulestreeitem.hpp \
		YAXCore/yaxkb.hpp \
		YAXCore/yaxmodels.hpp \
		YAXCore/yaxdomainsmodel.hpp \
		YAXCore/yaxvaluesmodel.hpp \
		YAXCore/yaxvariablesmodel.hpp \
		YAXCore/yaxrulesmodel.hpp \
		YAXCore/rulesdelegate.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) YAXCore/rulesdelegate.hpp -o moc_rulesdelegate.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.hpp \
		domainsdockwidget.hpp \
		YAXCore/yaxmodels.hpp \
		YAXCore/yaxkb.hpp \
		YAXCore/yaxdomainsmodel.hpp \
		YAXCore/yaxvaluesmodel.hpp \
		YAXCore/yaxvariablesmodel.hpp \
		YAXCore/yaxrulesmodel.hpp \
		YAXCore/rulestreeitem.hpp \
		variablesdockwidget.hpp \
		rulesdockwidget.hpp \
		YAXCore/rulesdelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.hpp \
		domainsdockwidget.hpp \
		YAXCore/yaxmodels.hpp \
		YAXCore/yaxkb.hpp \
		YAXCore/yaxdomainsmodel.hpp \
		YAXCore/yaxvaluesmodel.hpp \
		YAXCore/yaxvariablesmodel.hpp \
		YAXCore/yaxrulesmodel.hpp \
		YAXCore/rulestreeitem.hpp \
		variablesdockwidget.hpp \
		rulesdockwidget.hpp \
		YAXCore/rulesdelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

domainsdockwidget.o: domainsdockwidget.cpp domainsdockwidget.hpp \
		YAXCore/yaxmodels.hpp \
		YAXCore/yaxkb.hpp \
		YAXCore/yaxdomainsmodel.hpp \
		YAXCore/yaxvaluesmodel.hpp \
		YAXCore/yaxvariablesmodel.hpp \
		YAXCore/yaxrulesmodel.hpp \
		YAXCore/rulestreeitem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o domainsdockwidget.o domainsdockwidget.cpp

yaxmodels.o: YAXCore/yaxmodels.cpp YAXCore/yaxmodels.hpp \
		YAXCore/yaxkb.hpp \
		YAXCore/yaxdomainsmodel.hpp \
		YAXCore/yaxvaluesmodel.hpp \
		YAXCore/yaxvariablesmodel.hpp \
		YAXCore/yaxrulesmodel.hpp \
		YAXCore/rulestreeitem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o yaxmodels.o YAXCore/yaxmodels.cpp

variablesdockwidget.o: variablesdockwidget.cpp variablesdockwidget.hpp \
		YAXCore/yaxmodels.hpp \
		YAXCore/yaxkb.hpp \
		YAXCore/yaxdomainsmodel.hpp \
		YAXCore/yaxvaluesmodel.hpp \
		YAXCore/yaxvariablesmodel.hpp \
		YAXCore/yaxrulesmodel.hpp \
		YAXCore/rulestreeitem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o variablesdockwidget.o variablesdockwidget.cpp

rulesdockwidget.o: rulesdockwidget.cpp rulesdockwidget.hpp \
		YAXCore/yaxmodels.hpp \
		YAXCore/yaxkb.hpp \
		YAXCore/yaxdomainsmodel.hpp \
		YAXCore/yaxvaluesmodel.hpp \
		YAXCore/yaxvariablesmodel.hpp \
		YAXCore/yaxrulesmodel.hpp \
		YAXCore/rulestreeitem.hpp \
		YAXCore/rulesdelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rulesdockwidget.o rulesdockwidget.cpp

yaxvariablesmodel.o: YAXCore/yaxvariablesmodel.cpp YAXCore/yaxvariablesmodel.hpp \
		YAXCore/yaxkb.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o yaxvariablesmodel.o YAXCore/yaxvariablesmodel.cpp

yaxvaluesmodel.o: YAXCore/yaxvaluesmodel.cpp YAXCore/yaxvaluesmodel.hpp \
		YAXCore/yaxkb.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o yaxvaluesmodel.o YAXCore/yaxvaluesmodel.cpp

yaxdomainsmodel.o: YAXCore/yaxdomainsmodel.cpp YAXCore/yaxdomainsmodel.hpp \
		YAXCore/yaxkb.hpp \
		YAXCore/yaxmodels.hpp \
		YAXCore/yaxvaluesmodel.hpp \
		YAXCore/yaxvariablesmodel.hpp \
		YAXCore/yaxrulesmodel.hpp \
		YAXCore/rulestreeitem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o yaxdomainsmodel.o YAXCore/yaxdomainsmodel.cpp

yaxrulesmodel.o: YAXCore/yaxrulesmodel.cpp YAXCore/yaxrulesmodel.hpp \
		YAXCore/rulestreeitem.hpp \
		YAXCore/yaxkb.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o yaxrulesmodel.o YAXCore/yaxrulesmodel.cpp

rulestreeitem.o: YAXCore/rulestreeitem.cpp YAXCore/rulestreeitem.hpp \
		YAXCore/yaxkb.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rulestreeitem.o YAXCore/rulestreeitem.cpp

rulesdelegate.o: YAXCore/rulesdelegate.cpp YAXCore/rulesdelegate.hpp \
		YAXCore/rulestreeitem.hpp \
		YAXCore/yaxkb.hpp \
		YAXCore/yaxmodels.hpp \
		YAXCore/yaxdomainsmodel.hpp \
		YAXCore/yaxvaluesmodel.hpp \
		YAXCore/yaxvariablesmodel.hpp \
		YAXCore/yaxrulesmodel.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rulesdelegate.o YAXCore/rulesdelegate.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_domainsdockwidget.o: moc_domainsdockwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_domainsdockwidget.o moc_domainsdockwidget.cpp

moc_yaxmodels.o: moc_yaxmodels.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_yaxmodels.o moc_yaxmodels.cpp

moc_variablesdockwidget.o: moc_variablesdockwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_variablesdockwidget.o moc_variablesdockwidget.cpp

moc_rulesdockwidget.o: moc_rulesdockwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rulesdockwidget.o moc_rulesdockwidget.cpp

moc_yaxvariablesmodel.o: moc_yaxvariablesmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_yaxvariablesmodel.o moc_yaxvariablesmodel.cpp

moc_yaxvaluesmodel.o: moc_yaxvaluesmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_yaxvaluesmodel.o moc_yaxvaluesmodel.cpp

moc_yaxdomainsmodel.o: moc_yaxdomainsmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_yaxdomainsmodel.o moc_yaxdomainsmodel.cpp

moc_yaxrulesmodel.o: moc_yaxrulesmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_yaxrulesmodel.o moc_yaxrulesmodel.cpp

moc_rulesdelegate.o: moc_rulesdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rulesdelegate.o moc_rulesdelegate.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

